[terminal]
vt = 1
switch = true

[general]
runfile = "/run/greetd-hyprland.run"

[default_session]
command = "/usr/bin/env PATH=/home/blousy/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin tuigreet --cmd 'desktop-vt-session hyprland' --time"
user = "blousy"

[initial_session]
command = "/usr/bin/env PATH=/home/blousy/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin desktop-vt-session hyprland"
user = "blousy"
