general {
    ignore_dbus_inhibit = true
    ignore_systemd_inhibit = false
}

listener {
    timeout = 180
    on-timeout = $HOME/.config/hypr/scripts/idle-screensaver.sh start
    on-resume = $HOME/.config/hypr/scripts/idle-screensaver.sh stop
}
