---@diagnostic disable: undefined-global
local colors = {
	-- PATCH_OPEN
	Normal = { fg = "#DDD4B3", bg = "#000000" },
	Boolean = { fg = "#D88745", bold = true },
	Character = { fg = "#B68A65" },
	ColorColumn = { bg = "#2C2823" },
	VertSplit = { link = "ColorColumn" },
	Comment = { fg = "#70685B", italic = true },
	Conditional = { fg = "#B16A3D" },
	Label = { link = "Conditional" },
	Constant = { fg = "#D88745", bold = true },
	CurSearch = { fg = "#222222", bg = "#D88745", bold = true },
	CursorColumn = { bg = "#282521" },
	CursorLine = { bg = "#282521" },
	CursorLineNr = { fg = "#D88745", bg = "#282521", bold = true },
	Debug = { fg = "#D88745", bold = true },
	Define = { fg = "#B16A3D" },
	Delimiter = { fg = "#DDD4B3" },
	Directory = { fg = "#C2864D" },
	EndOfBuffer = { fg = "#49382B" },
	Error = { fg = "#C15F45" },
	Exception = { fg = "#C15F45" },
	Float = { fg = "#C2864D" },
	FloatBorder = { fg = "#765039", bg = "#1C1C1C" },
	FloatTitle = { fg = "#D88745", bg = "#1C1C1C", bold = true },
	Function = { fg = "#C2864D" },
	Identifier = { fg = "#DDD4B3" },
	Ignore = {},
	IncSearch = { fg = "#222222", bg = "#D88745" },
	Include = { fg = "#B16A3D" },
	Keyword = { fg = "#B16A3D" },
	LineNr = { fg = "#70685B" },
	LineNrAbove = { fg = "#594B40", italic = true },
	LineNrBelow = { link = "LineNrAbove" },
	Macro = { fg = "#C2864D" },
	MatchParen = { fg = "#D88745", bold = true, underline = true },
	ModeMsg = { fg = "#D88745", bold = true },
	MoreMsg = { link = "ModeMsg" },
	NonText = { fg = "#49382B" },
	NormalFloat = { fg = "#DDD4B3", bg = "#1C1C1C" },
	Number = { fg = "#C2864D" },
	Operator = { fg = "#DDD4B3" },
	Pmenu = { fg = "#DDD4B3", bg = "#1C1C1C" },
	PmenuSel = { fg = "#222222", bg = "#D88745", bold = true },
	PreCondit = { fg = "#B16A3D" },
	PreProc = { fg = "#B16A3D" },
	Question = { fg = "#D88745" },
	QuickFixLine = { fg = "#D88745", bg = "#2C2823" },
	Repeat = { fg = "#B16A3D" },
	Search = { fg = "#222222", bg = "#C2864D" },
	Special = { fg = "#D88745" },
	SpecialChar = { fg = "#D88745" },
	SpecialComment = { fg = "#D88745", bold = true, italic = true },
	Statement = { fg = "#B16A3D" },
	StatusLine = { fg = "#DDD4B3", bold = true },
	StatusLineNC = { fg = "#70685B" },
	StorageClass = { fg = "#B16A3D" },
	String = { fg = "#B68A65" },
	Structure = { fg = "#71875A", bold = true },
	Tag = { fg = "#B16A3D" },
	Todo = { fg = "#D88745", bold = true },
	Type = { fg = "#71875A", bold = true },
	Typedef = { fg = "#71875A", bold = true },
	Underlined = { underline = true },
	Visual = { bg = "#4A3527" },
	WinSeparator = { fg = "#765039" },
	-- PATCH_CLOSE
	-- Added by me as needed
	htmlEndTag = { link = "Function" },
	typescriptEndColons = { link = "Identifier" },
	typescriptVariable = { link = "Function" },
	typescriptTypeReference = { link = "Function" },
	typescriptOperator = { link = "Function" },
	typescriptIdentifierName = { link = "Function" },
	["@constructor"] = { fg = "#D88745", bold = true },
	["@constant"] = { fg = "#D88745", bold = true },
	["@constant.builtin"] = { fg = "#D88745", bold = true },
	["@function"] = { link = "Function" },
	["@function.call"] = { link = "Function" },
	["@function.macro"] = { link = "Function" },
	["@keyword"] = { link = "Keyword" },
	["@number"] = { link = "Number" },
	["@string"] = { link = "String" },
	["@type"] = { link = "Type" },
	["@type.builtin"] = { fg = "#71875A" },
	BlinkCmpMenu = { fg = "#DDD4B3", bg = "#1C1C1C" },
	BlinkCmpMenuBorder = { fg = "#765039", bg = "#1C1C1C" },
	BlinkCmpMenuSelection = { fg = "#222222", bg = "#D88745", bold = true },
	BlinkCmpLabel = { fg = "#DDD4B3" },
	BlinkCmpLabelDescription = { fg = "#70685B" },
	BlinkCmpLabelDetail = { fg = "#70685B" },
	BlinkCmpKind = { fg = "#71875A", bold = true },
	BlinkCmpSource = { fg = "#B68A65" },
	BlinkCmpDoc = { fg = "#DDD4B3", bg = "#1C1C1C" },
	BlinkCmpDocBorder = { fg = "#765039", bg = "#1C1C1C" },
}

vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='dune'")

for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
